name: 'PR description checker'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jadrol/pr-description-checker-action@v1.0.0
        id: description
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          #exempt-labels: no qa
          continue-on-error: true
      - name: comtt
        if: steps.description.outputs.exit_status != 0 
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Example of message !'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
